/** Product analytics events sent to PostHog. Values are the event names stored there. */
export enum AnalyticsEvent {
  AccountCreated = 'account_created',
  AccountRegistered = 'account_registered',
  AuthCompleted = 'auth_completed',
  AuthFailed = 'auth_failed',
  AuthStarted = 'auth_started',
  BudgetCreated = 'budget_created',
  BudgetUpdated = 'budget_updated',
  CategoryCreated = 'category_created',
  ColillaDocumentSaved = 'colilla_document_saved',
  ColillaImportCompleted = 'colilla_import_completed',
  ColillaImportFailed = 'colilla_import_failed',
  ColillaImportStarted = 'colilla_import_started',
  FeedbackOpened = 'feedback_opened',
  FeedbackSubmitted = 'feedback_submitted',
  PlanCreated = 'plan_created',
  PlanDuplicated = 'plan_duplicated',
  PlanItemCreated = 'plan_item_created',
  PlanItemPaymentStatusChanged = 'plan_item_payment_status_changed',
  PlanItemUpdated = 'plan_item_updated',
  PlanItemsMerged = 'plan_items_merged',
  PublicMenuOpened = 'public_menu_opened',
  PublicNavigationSelected = 'public_navigation_selected',
  PwaInstallPromptShown = 'pwa_install_prompt_shown',
  PwaInstalled = 'pwa_installed',
  RefundCreated = 'refund_created',
  RefundUpdated = 'refund_updated',
  SupportContactClicked = 'support_contact_clicked',
  TagCreated = 'tag_created',
  TransactionCreated = 'transaction_created',
  TransactionUpdated = 'transaction_updated',
  TransferCreated = 'transfer_created',
}
